spring.application.name=nestaway-backend

spring.datasource.url=jdbc:mysql://localhost:3306/nestaway_db
spring.datasource.username=root
spring.datasource.password=java1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT Config
jwt.secret=nestaway-super-secret-key-nestaway-super-secret-key-123456
jwt.expiration-ms=7200000