spring.application.name=nestaway-backend

# Server Port
server.port=${PORT:8080}

# Database Config (Local Fallback + Cloud Override)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/nestaway_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:java1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
jwt.secret=${JWT_SECRET:nestaway-super-secret-key-nestaway-super-secret-key-123456}
jwt.expiration-ms=7200000